### LOCAL TEST ----------------------------------

POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName" : "Dylan",
    "lastName" : "Ayon",
    "email" : "dayon@email.com",
    "favoriteColor" : "Rojo, Azul",
    "birthday" : "November 18th"
}

###

PUT http://localhost:3000/contacts/644c3f2f9eff72c365752397 HTTP/1.1
content-type: application/json

{
    "firstName" : "Angel",
    "lastName" : "Lugo",
    "email" : "angelo@email.com",
    "favoriteColor" : "Yellow",
    "birthday" : "July 30th"
}

###

DELETE http://localhost:3000/contacts/644c3e4e0c3d382125a21b50 HTTP/1.1

### RENDER TEST ----------------------------------

POST https://lesson-1-cse341-angel.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName" : "Dylan",
    "lastName" : "Ayon",
    "email" : "dayon@email.com",
    "favoriteColor" : "Rojo, Azul",
    "birthday" : "November 18th"
}

###

PUT https://lesson-1-cse341-angel.onrender.com/contacts/644c3f2f9eff72c365752397 HTTP/1.1
content-type: application/json

{
    "firstName" : "Angel",
    "lastName" : "Lugo",
    "email" : "angelo@email.com",
    "favoriteColor" : "Green",
    "birthday" : "July 30th"
}

###

DELETE https://lesson-1-cse341-angel.onrender.com/contacts/6444291082f5939072d71b02 HTTP/1.1